theme: jekyll-theme-tactile
title: R.J. Graham
description: Investigating the habitability of Earth & Earth-like planets
collections:
  About:
    output: true
    permalink: /:collection/:path/
  Research:
    output: true
    permalink: /:collection/:path/
